[project]
name = "myrient-search-app"
version = "0.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.0",
    "pyinstaller>=6.15.0",
    "requests>=2.32.4",
    "textual>=6.6.0",
    "textual-serve>=1.1.3",
]
